import type { ThemeConfig } from 'antd';

export const lightTheme: ThemeConfig = {
  token: {
    // Single source of truth: CSS custom properties from styles/tokens.css
    // (specifically the [data-theme="light"] block).
    colorBgBase:          'var(--bg-page)',
    colorBgContainer:     'var(--bg-surface)',
    colorBgElevated:      'var(--bg-elevated)',
    colorBgLayout:        'var(--bg-page)',
    colorBgSpotlight:     'var(--bg-hover)',
    colorBorder:          'var(--border)',
    colorBorderSecondary: 'var(--border-strong)',
    colorTextBase:        'var(--text-primary)',
    colorText:            'var(--text-primary)',
    colorTextSecondary:   'var(--text-secondary)',
    colorTextTertiary:    'var(--text-tertiary)',
    colorTextQuaternary:  'var(--text-disabled)',
    colorPrimary:         '#16a34a',
    colorSuccess:         '#16a34a',
    colorError:           '#ef4444',
    colorWarning:         '#f59e0b',
    colorInfo:            '#3b82f6',
    colorLink:            '#3b82f6',
    colorLinkHover:       '#2563eb',
    borderRadius:         8,
    borderRadiusLG:       12,
    borderRadiusSM:       6,
    fontFamily:           "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:             13,
    fontSizeLG:           15,
    lineHeight:           1.5,
    controlHeight:        36,
    controlHeightLG:      40,
    boxShadow:            '0 1px 2px rgba(0,0,0,0.05)',
    boxShadowSecondary:   '0 2px 4px rgba(0,0,0,0.06)',
  },
  components: {
    Layout: {
      siderBg:      'var(--bg-surface)',
      headerBg:     'var(--bg-surface)',
      bodyBg:       'var(--bg-page)',
      triggerBg:    'var(--bg-hover)',
      triggerColor: 'var(--text-secondary)',
    },
    Menu: {
      itemBg:              'var(--bg-surface)',
      subMenuItemBg:       'var(--bg-surface)',
      itemSelectedBg:      'var(--brand-muted)',
      itemHoverBg:         'var(--bg-hover)',
      itemColor:           'var(--text-secondary)',
      itemSelectedColor:   'var(--brand)',
      itemHoverColor:      'var(--text-primary)',
      itemBorderRadius:    8,
    },
    Card: {
      colorBgContainer:     'var(--bg-surface)',
      colorBorderSecondary: 'var(--border)',
      borderRadiusLG:       12,
      paddingLG:            20,
      boxShadow:            '0 1px 2px rgba(0,0,0,0.05)',
    },
    Table: {
      colorBgContainer:   'transparent',
      headerBg:           'var(--bg-page)',
      headerColor:        'var(--text-secondary)',
      headerSortActiveBg: 'var(--bg-hover)',
      rowHoverBg:         'var(--bg-hover)',
      borderColor:        'var(--border)',
      colorText:          'var(--text-primary)',
      colorTextHeading:   'var(--text-secondary)',
    },
    Button: {
      colorPrimary:            'var(--brand)',
      colorPrimaryHover:       'var(--brand-hover)',
      colorPrimaryActive:      '#166534',
      primaryShadow:           'none',
      primaryColor:            '#ffffff',
      borderRadius:            8,
      borderRadiusSM:          4,
      defaultBg:               'var(--bg-surface)',
      defaultColor:            'var(--text-primary)',
      defaultBorderColor:      'var(--border-hover)',
      defaultHoverBg:          'var(--bg-hover)',
      defaultHoverColor:       'var(--text-primary)',
      defaultHoverBorderColor: 'var(--brand)',
    },
    Input: {
      colorBgContainer:     'var(--bg-surface)',
      colorBorder:          'var(--border-hover)',
      colorText:            'var(--text-primary)',
      colorTextPlaceholder: 'var(--text-tertiary)',
      hoverBorderColor:     'var(--brand)',
      activeBorderColor:    'var(--brand)',
      activeShadow:         '0 0 0 2px var(--brand-muted)',
    },
    Select: {
      colorBgContainer:     'var(--bg-surface)',
      colorBorder:          'var(--border-hover)',
      colorText:            'var(--text-primary)',
      colorTextPlaceholder: 'var(--text-tertiary)',
      optionSelectedBg:     'var(--brand-muted)',
      optionActiveBg:       'var(--bg-hover)',
      colorBgElevated:      'var(--bg-surface)',
    },
    Modal: {
      colorBgElevated: 'var(--bg-surface)',
      colorBorder:     'var(--border)',
      titleColor:      'var(--text-primary)',
    },
    Drawer: {
      colorBgElevated: 'var(--bg-surface)',
    },
    Dropdown: {
      colorBgElevated:    'var(--bg-surface)',
      colorText:          'var(--text-primary)',
      controlItemBgHover: 'var(--bg-hover)',
    },
    Tooltip: {
      colorBgSpotlight:    'var(--text-primary)',
      colorTextLightSolid: 'var(--bg-surface)',
    },
    Pagination: {
      colorBgContainer: 'var(--bg-surface)',
      colorText:        'var(--text-secondary)',
      itemActiveBg:     'var(--brand-muted)',
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize:   11,
    },
    Badge: {
      colorBgContainer: 'var(--bg-surface)',
    },
    Tag: {
      defaultBg:    'var(--bg-hover)',
      defaultColor: 'var(--text-secondary)',
    },
    Divider: {
      colorSplit: 'var(--border)',
    },
    Spin: {
      colorPrimary: 'var(--brand)',
    },
    Progress: {
      colorSuccess: 'var(--brand)',
    },
    Alert: {
      colorSuccessBg:     'var(--success-bg)',
      colorSuccessBorder: 'var(--brand-border)',
      colorErrorBg:       'var(--error-bg)',
      colorErrorBorder:   'rgba(239, 68, 68, 0.15)',
      colorWarningBg:     'var(--warning-bg)',
      colorWarningBorder: 'rgba(245, 158, 11, 0.15)',
      colorInfoBg:        'var(--info-bg)',
      colorInfoBorder:    'rgba(59, 130, 246, 0.15)',
    },
    DatePicker: {
      colorBgContainer:     'var(--bg-surface)',
      colorBorder:          'var(--border-hover)',
      colorText:            'var(--text-primary)',
      colorTextPlaceholder: 'var(--text-tertiary)',
      colorBgElevated:      'var(--bg-surface)',
    },
    Form: {
      labelColor:    'var(--text-secondary)',
      labelFontSize: 12,
    },
    Typography: {
      colorText:           'var(--text-primary)',
      colorTextSecondary:  'var(--text-secondary)',
      colorTextDisabled:   'var(--text-tertiary)',
      colorLink:           'var(--info)',
      titleMarginBottom:   '0.5em',
    },
    Result: {
      colorTextDescription: 'var(--text-secondary)',
    },
    Empty: {
      colorTextDisabled: 'var(--text-tertiary)',
    },
    Notification: {
      colorBgElevated: 'var(--bg-surface)',
      colorText:       'var(--text-primary)',
    },
    Message: {
      colorBgElevated: 'var(--bg-surface)',
      colorText:       'var(--text-primary)',
    },
  },
  algorithm: undefined,
};
