import type { ThemeConfig } from 'antd';

export const lightTheme: ThemeConfig = {
  token: {
    // Single source of truth: CSS custom properties from styles/tokens.css
    // (specifically the [data-theme="light"] block).
    colorBgBase:          'var(--bg-page)',
    colorBgContainer:     'var(--bg-surface)',
    colorBgElevated:      'var(--bg-elevated)',
    colorBgLayout:        'var(--bg-page)',
    colorBgSpotlight:     'var(--bg-hover)',
    colorBorder:          'var(--border)',
    colorBorderSecondary: 'var(--border-strong)',
    colorTextBase:        'var(--text-primary)',
    colorText:            'var(--text-primary)',
    colorTextSecondary:   'var(--text-secondary)',
    colorTextTertiary:    'var(--text-tertiary)',
    colorTextQuaternary:  'var(--text-disabled)',
    colorPrimary:         '#16a34a',
    colorSuccess:         '#16a34a',
    colorError:           '#ef4444',
    colorWarning:         '#f59e0b',
    colorInfo:            '#3b82f6',
    colorLink:            '#3b82f6',
    colorLinkHover:       '#2563eb',
    borderRadius:         8,
    borderRadiusLG:       12,
    borderRadiusSM:       6,
    fontFamily:           "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize:             13,
    fontSizeLG:           15,
    lineHeight:           1.5,
    controlHeight:        36,
    controlHeightLG:      40,
    boxShadow:            '0 1px 2px rgba(0,0,0,0.05)',
    boxShadowSecondary:   '0 2px 4px rgba(0,0,0,0.06)',
  },
  components: {
    Layout: {
      siderBg:      '#ffffff',
      headerBg:     '#ffffff',
      bodyBg:       '#fafafa',
      triggerBg:    '#f0f0f0',
      triggerColor: '#525252',
    },
    Menu: {
      itemBg:              '#ffffff',
      subMenuItemBg:       '#ffffff',
      itemSelectedBg:      'rgba(22, 163, 74, 0.08)',
      itemHoverBg:         '#f5f5f5',
      itemColor:           '#525252',
      itemSelectedColor:   '#16a34a',
      itemHoverColor:      '#171717',
      itemBorderRadius:    8,
    },
    Card: {
      colorBgContainer:     '#ffffff',
      colorBorderSecondary: '#e5e5e5',
      borderRadiusLG:       12,
      paddingLG:            20,
      boxShadow:            '0 1px 2px rgba(0,0,0,0.05)',
    },
    Table: {
      colorBgContainer:   'transparent',
      headerBg:           '#fafafa',
      headerColor:        '#525252',
      headerSortActiveBg: '#f0f0f0',
      rowHoverBg:         '#f5f5f5',
      borderColor:        '#e5e5e5',
      colorText:          '#171717',
      colorTextHeading:   '#525252',
    },
    Button: {
      colorPrimary:            '#16a34a',
      colorPrimaryHover:       '#15803d',
      colorPrimaryActive:      '#166534',
      primaryShadow:           'none',
      primaryColor:            '#ffffff',
      borderRadius:            8,
      borderRadiusSM:          4,
      defaultBg:               '#ffffff',
      defaultColor:            '#171717',
      defaultBorderColor:      '#d4d4d4',
      defaultHoverBg:          '#f5f5f5',
      defaultHoverColor:       '#171717',
      defaultHoverBorderColor: '#4a9eff',
    },
    Input: {
      colorBgContainer:     '#ffffff',
      colorBorder:          '#d4d4d4',
      colorText:            '#171717',
      colorTextPlaceholder: '#a3a3a3',
      hoverBorderColor:     '#4a9eff',
      activeBorderColor:    '#4a9eff',
      activeShadow:         '0 0 0 2px rgba(74, 158, 255, 0.15)',
    },
    Select: {
      colorBgContainer:     '#ffffff',
      colorBorder:          '#d4d4d4',
      colorText:            '#171717',
      colorTextPlaceholder: '#a3a3a3',
      optionSelectedBg:     'rgba(22, 163, 74, 0.08)',
      optionActiveBg:       '#f5f5f5',
      colorBgElevated:      '#ffffff',
    },
    Modal: {
      colorBgElevated: '#ffffff',
      colorBorder:     '#e5e5e5',
      titleColor:      '#171717',
    },
    Drawer: {
      colorBgElevated: '#ffffff',
    },
    Dropdown: {
      colorBgElevated:    '#ffffff',
      colorText:          '#171717',
      controlItemBgHover: '#f5f5f5',
    },
    Tooltip: {
      colorBgSpotlight:    '#171717',
      colorTextLightSolid: '#ffffff',
    },
    Pagination: {
      colorBgContainer: '#ffffff',
      colorText:        '#525252',
      itemActiveBg:     'rgba(22, 163, 74, 0.08)',
    },
    Statistic: {
      contentFontSize: 28,
      titleFontSize:   11,
    },
    Badge: {
      colorBgContainer: '#ffffff',
    },
    Tag: {
      defaultBg:    '#f0f0f0',
      defaultColor: '#525252',
    },
    Divider: {
      colorSplit: '#e5e5e5',
    },
    Spin: {
      colorPrimary: '#16a34a',
    },
    Progress: {
      colorSuccess: '#16a34a',
    },
    Alert: {
      colorSuccessBg:     'rgba(16, 185, 129, 0.06)',
      colorSuccessBorder: 'rgba(16, 185, 129, 0.15)',
      colorErrorBg:       'rgba(239, 68, 68, 0.06)',
      colorErrorBorder:   'rgba(239, 68, 68, 0.15)',
      colorWarningBg:     'rgba(245, 158, 11, 0.06)',
      colorWarningBorder: 'rgba(245, 158, 11, 0.15)',
      colorInfoBg:        'rgba(59, 130, 246, 0.06)',
      colorInfoBorder:    'rgba(59, 130, 246, 0.15)',
    },
    DatePicker: {
      colorBgContainer:     '#ffffff',
      colorBorder:          '#d4d4d4',
      colorText:            '#171717',
      colorTextPlaceholder: '#a3a3a3',
      colorBgElevated:      '#ffffff',
    },
    Form: {
      labelColor:    '#525252',
      labelFontSize: 12,
    },
    Typography: {
      colorText:           '#171717',
      colorTextSecondary:  '#525252',
      colorTextDisabled:   '#a3a3a3',
      colorLink:           '#3b82f6',
      titleMarginBottom:   '0.5em',
    },
    Result: {
      colorTextDescription: '#525252',
    },
    Empty: {
      colorTextDisabled: '#a3a3a3',
    },
    Notification: {
      colorBgElevated: '#ffffff',
      colorText:       '#171717',
    },
    Message: {
      colorBgElevated: '#ffffff',
      colorText:       '#171717',
    },
  },
  algorithm: undefined,
};
